"""
Load Pre-Computed Statistics for Dashboard

This module loads the JSON statistics file generated by generate_dashboard_data.py
"""

import json
from pathlib import Path
from typing import Dict, Any
import streamlit as st


@st.cache_data
def load_statistics() -> Dict[str, Any]:
    """
    Load pre-computed statistics from JSON file.
    
    Uses Streamlit's cache to avoid reloading on every interaction.
    
    Returns
    -------
    Dict[str, Any]
        Complete statistics dictionary
        
    Raises
    ------
    FileNotFoundError
        If statistics file doesn't exist
    """
    # Try to find the stats file
    current_dir = Path(__file__).parent.parent
    stats_file = current_dir.parent / 'data' / 'processed' / 'dashboard_statistics.json'
    
    if not stats_file.exists():
        raise FileNotFoundError(
            f"Statistics file not found at {stats_file}\n"
            "Please run: python src/scripts/generate_dashboard_data.py"
        )
    
    with open(stats_file, 'r') as f:
        data = json.load(f)
    
    return data


def get_country_stats(stats: Dict[str, Any], country: str) -> Dict[str, Any]:
    """
    Get statistics for a specific country.
    
    Parameters
    ----------
    stats : Dict
        Complete statistics dictionary
    country : str
        Country name (lowercase)
        
    Returns
    -------
    Dict
        Country-specific statistics
    """
    return stats['countries'].get(country, {})


def get_comparison_stats(stats: Dict[str, Any]) -> Dict[str, Any]:
    """
    Get cross-country comparison statistics.
    
    Parameters
    ----------
    stats : Dict
        Complete statistics dictionary
        
    Returns
    -------
    Dict
        Comparison statistics
    """
    return stats.get('comparison', {})


def get_metadata(stats: Dict[str, Any]) -> Dict[str, Any]:
    """
    Get metadata about the statistics.
    
    Parameters
    ----------
    stats : Dict
        Complete statistics dictionary
        
    Returns
    -------
    Dict
        Metadata information
    """
    return stats.get('metadata', {})
